version: "3.8"

services:
  postgres:
    image: postgres:14
    restart: always
    container_name: startup-call-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: startup_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  startup-call-service:
    build: .
    container_name: startup-call-service
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    env_file:
      - .env
    environment:
      DATABASE_URL: postgres://user:password@postgres:5432/startup_db

volumes:
  postgres_data:
